spring:
    flyway:
        enabled: true
        default-schema: jobapps
        schemas: jobapps
        baseline-on-migrate: true
        baseline-version: 1

server:
    port: ${SERVER_PORT:8080}
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param